[workspace]
members = ["crates/quichash-core", "crates/quichash-cli"]
default-members = ["crates/quichash-core", "crates/quichash-cli"]
resolver = "2"

[profile.release]
opt-level = 3
lto = "fat"
strip = true
panic = "abort"
codegen-units = 1
incremental = false

[profile.bench]
inherits = "release"
